#pragma once

// This file simulates some library and does nothing.
// It exists just to make the compilation possible.
// Do not edit this file.

#include <mutex>

namespace lib
{
    inline std::mutex* getMutex()
    {
        static std::mutex mutex;
        return &mutex;
    }

    inline int getDefaultFactor()
    {
        return 0;
    }

    struct Physical_device
    {
        Physical_device(int)
        {}
    };

    inline int getHardware(int)
    {
        return 0;
    }
}
